### ISSUE TITLE
PropUpdate

### ISSUE THREAD

**Issue by yvincentsmatechnologies** [SMATechnologies/opcon-cli-java#15]
the -pe parameter does not work with the PropUpdate function.
Without this parameter the PropUpdate function works correctly.

Whit -pe
![-pe](https://user-images.githubusercontent.com/62431578/110122510-01a95700-7dc0-11eb-8859-794bbda9c1ea.PNG)
Whitout -pe
![-sanspe](https://user-images.githubusercontent.com/62431578/110122716-41703e80-7dc0-11eb-943c-4b980c9f9ef4.PNG)

**Comment by Bertievh** [comment]
The documentation is misleading and will be corrected.
the -pe is a boolean condition. to indicate encryption, include the -pe argument (no values).
when the -pe argument is not present encryption is false
-t PropUpdate -pn Prop001 -pv newValue -pe                 (for encrypted property)
-t PropUpdate -pn Prop001 -pv newValue                        (for non-encrypted property)
