### ISSUE TITLE
Correction of the documentation.

### ISSUE THREAD

**Issue by yvincentsmatechnologies** [SMATechnologies/opcon-cli-java#5]
Hello,

Can you change the Opcon-CLI-JAVA documentation?

Indeed there is an error concerning the json template. It's necessary to put a [ at the beginning of the template and one ] at the end.

Thank you

**Comment by oeil** [comment]
@Bertievh I let you double-check that the connector expects the brackets [ ] in the JSON passed to create a new machine.

**Comment by Bertievh** [comment]
Corrected documentation to indicate [ ] required for MachAdd function and added wlimited function to MachAction function.
